# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='visitor', max_length=256, verbose_name='Commentator')),
                ('discription', models.TextField(verbose_name='description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(0, "Clothing and Accessories"), (1, "Eletricals"),
                                                    (2, "Food"), (3, "Sport and Leisure"),
                                                    (4, "Furniture"), (5, "Beauty")], verbose_name='category')),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('discription', models.TextField(verbose_name='description')),
                ('has_sale', models.IntegerField(default=0, verbose_name='purchase num')),
                ('pic', models.ImageField(upload_to='img', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('counts', models.IntegerField(verbose_name='inventory')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'product',
            },
        ),
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True, verbose_name='order id')),
                ('classification', models.IntegerField(choices=[(0, "Clothing and Accessories"), (1, "Eletricals"),
                                                    (2, "Food"), (3, "Sport and Leisure"),
                                                    (4, "Furniture"), (5, "Beauty")], verbose_name='category')),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('discription', models.TextField(verbose_name='description')),
                ('pic', models.ImageField(upload_to='img', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.IntegerField(choices=[(-1, 'in the list'), (0, 'not receive'), (1, 'received')], verbose_name='state')),
                ('count', models.IntegerField(verbose_name='purchase amount')),
                ('adress', models.CharField(default='', max_length=256, verbose_name='trading address')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='purchsing time')),
            ],
            options={
                'verbose_name': 'purchase record',
                'verbose_name_plural': 'purchase record',
            },
        ),
    ]
