# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='游客', max_length=256, verbose_name='评论人')),
                ('discription', models.TextField(verbose_name='描述')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(0, '服装首饰'), (1, '家电数码'), (2, '美食生鲜'), (3, '美食生鲜'), (4, '日用百货'), (5, '美妆洗护')], verbose_name='分类')),
                ('name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('discription', models.TextField(verbose_name='描述')),
                ('has_sale', models.IntegerField(default=0, verbose_name='付款人数')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('counts', models.IntegerField(verbose_name='库存')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True, verbose_name='订单编号')),
                ('classification', models.IntegerField(choices=[(0, '服装首饰'), (1, '家电数码'), (2, '美食生鲜'), (3, '运动乐器'), (4, '日用百货'), (5, '美妆洗护')], verbose_name='分类')),
                ('name', models.CharField(max_length=256, verbose_name='商品名称')),
                ('discription', models.TextField(verbose_name='描述')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.IntegerField(choices=[(-1, '购物车中'), (0, '未收货'), (1, '已收货')], verbose_name='状态')),
                ('count', models.IntegerField(verbose_name='购买数量')),
                ('adress', models.CharField(default='', max_length=256, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人手机号')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
            ],
            options={
                'verbose_name': '购买记录',
                'verbose_name_plural': '购买记录',
            },
        ),
    ]
