# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:47
from __future__ import unicode_literals

import WebShop.system.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0002_goodsrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_image_url', models.URLField(verbose_name='third party url address')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebShop.GoodsRecord')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(storage=WebShop.system.storage.ImageStorage(), upload_to='img', verbose_name='image'),
        ),
    ]
