# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0003_auto_20190102_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimage',
            name='goods',
        ),
        migrations.DeleteModel(
            name='GoodsImage',
        ),
    ]
