# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0004_auto_20190102_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(upload_to='img', verbose_name='iamge'),
        ),
    ]
