# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-02 21:51
from __future__ import unicode_literals

import WebShop.system.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShop', '0005_auto_20190102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pic',
            field=models.ImageField(storage=WebShop.system.storage.ImageStorage(), upload_to='img', verbose_name='image'),
        ),
    ]
